spring.application.name=active-campaign-integration

# ActiveCampaign API
activecampaign.api.url=${AC_API_URL}
activecampaign.api.key=${AC_API_KEY}

# Schedulers
app.scheduler.timezone=Europe/Rome
app.scheduler.contact-sync.cron=10 * * * * *
app.scheduler.contact-sync.cron.active=false
app.scheduler.contact-bulk-import.cron=10 * * * * *
app.scheduler.contact-bulk-import.cron.active=false
